### ISSUE TITLE
Firefox Font Weight Renders Too Bold

### ISSUE THREAD

**Issue by danilowoz** [Significa/significa.co#51]
![Screenshot 2019-05-16 at 11 11 28](https://user-images.githubusercontent.com/4838076/57846166-854d1a80-77cb-11e9-82d6-54b6968c9f04.png)

Possible solution:

```css
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
```

or

```css
/**
 * Fix fonts that render as bold in Firefox
 *
 * Put this near the top of your style.css
 * Before any overriding styles
 */

html {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  font-smoothing: antialiased;
  font-weight: 400;
}

/**
 * Firefox specific rule
 */

@-moz-document url-prefix() {
  body {
    font-weight: lighter !important;
  }
}
```
